### ISSUE TITLE
how to use conda install torchnet?

### ISSUE THREAD

**Issue by qilong-zhang** [pytorch/tnt#118]
In my ubuntu sever, pip is ok, but torchnet is only in 'pip list' and not in 'conda list',  so when i run xx.py, error is no module named 'torchnet'. So i want to ask if i can use conda to install torchnet and how to install it? could anyone help me? thanks!

**Comment by szagoruyko** [comment]
why not use pip ?

**Comment by Zethson** [comment]
Please add create a conda package for torchnet. Complex programs require advanced dependency resolvement and for reproducibility reasons Conda packages are vital.

**Comment by mgroth0** [comment]
converting pypi packages to conda packages and uploading them is simple. A bit tedius, but step by step instructions here work: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html. I've created a few with no issues.

**Comment by LazWorm** [comment]
I met the same problem, torchnet in my pip list but not in conda list because I used "python setup.py build/install" to install it. Then I tried another way. Download zip and uncompressed it, then activate conda env, use "pip install /tnt-master/", It works(Windows and Ubuntu)! You can get more from: https://www.jianshu.com/p/024bb8027ff2

**Comment by qilong-zhang** [comment]
thanks~
